VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "BHidup"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private PONEbH, PTWObH, PTHREEbH, PFOURbH, PFIVEbH

Private PSIXbH, PSEVENbH, PEIGHTbH, PNINEbH, PTENbH

Private PELEVENbH

Public Function BHidup_ONE_D()
   BHidup_ONE_D = PONEbH
End Function
Public Property Let Value9(Setting)
   PONEbH = Setting
End Property

Public Function BHidup_TWO_D()
   BHidup_TWO_D = PTWObH
End Function
Public Property Let Value10(Setting)
   PTWObH = Setting
End Property

Public Function BHidup_THREE_D()
   BHidup_THREE_D = PTHREEbH
End Function
Public Property Let Value11(Setting)
   PTHREEbH = Setting
End Property

Public Function BHidup_FOUR_D()
   BHidup_FOUR_D = PFOURbH
End Function
Public Property Let Value12(Setting)
   PFOURbH = Setting
End Property

Public Function BHidup_ONE_C()
   BHidup_ONE_C = PFIVEbH
End Function
Public Property Let Value13(Setting)
   PFIVEbH = Setting
End Property

Public Function BHidup_TWO_C()
   BHidup_TWO_C = PSIXbH
End Function
Public Property Let Value14(Setting)
  PSIXbH = Setting
End Property

Public Function BHidup_THREE_C()
   BHidup_THREE_C = PSEVENbH
End Function
Public Property Let Value15(Setting)
  PSEVENbH = Setting
End Property

Public Function BHidup_ONE_B()
   BHidup_ONE_B = PEIGHTbH
End Function
Public Property Let Value16(Setting)
   PEIGHTbH = Setting
End Property

Public Function BHidup_TWO_B()
   BHidup_TWO_B = PNINEbH
End Function
Public Property Let Value17(Setting)
   PNINEbH = Setting
End Property

Public Function BHidup_ONE_A()
   BHidup_ONE_A = PTENbH
End Function
Public Property Let Value18(Setting)
   PTENbH = Setting
End Property

Public Function BHidup_FOUR_A()
  BHidup_FOUR_A = PELEVENbH
End Function
Public Property Let Value19(Setting)
   PELEVENbH = Setting
End Property
